# Generated by Django 5.0.6 on 2024-06-09 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.IntegerField()),
                ('schedule_start_date', models.DateTimeField()),
                ('schedule_end_date', models.DateTimeField()),
                ('class_meeting_start_time', models.DateTimeField()),
                ('class_meeting_end_time', models.DateTimeField()),
                ('class_meeting_day_pattern_code', models.CharField(max_length=10)),
                ('class_meeting_week_pattern_code', models.CharField(max_length=10)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255, null=True)),
                ('course_offer_number', models.IntegerField()),
                ('subject_code', models.CharField(max_length=255, null=True)),
                ('catalog_number', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('course_component_code', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('class_section', models.IntegerField()),
                ('course_component', models.CharField(max_length=255)),
                ('max_enrollment_capacity', models.IntegerField()),
                ('schedule_data', models.ManyToManyField(to='fetcher.rawclassschedule')),
            ],
        ),
    ]
