# Generated by Django 5.0.6 on 2024-06-09 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.IntegerField()),
                ('class_meeting_start_time', models.TimeField()),
                ('class_meeting_end_time', models.TimeField()),
                ('class_meeting_day_pattern_code', models.CharField(max_length=31)),
                ('class_meeting_week_pattern_code', models.CharField(max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='RawCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=31, null=True)),
                ('subject_code', models.CharField(max_length=31, null=True)),
                ('catalog_number', models.CharField(max_length=31, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('course_component_code', models.CharField(max_length=31, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidClassSchedules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=31)),
                ('valid_schedules', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='RawClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=31)),
                ('class_section', models.IntegerField()),
                ('course_component', models.CharField(max_length=31)),
                ('schedule_data', models.ManyToManyField(to='fetcher.rawclassschedule')),
            ],
        ),
    ]
