# Generated by Django 5.0.8 on 2024-08-25 08:51

from django.db import migrations
from django.core.management import call_command


def run_initialization_commands(apps, schema_editor):

    # Run the commands
    call_command('fetch_courses')
    call_command('compute_class_schedules')

class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(run_initialization_commands),
    ]
