# Generated by Django 5.0.6 on 2024-06-11 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursesOverlap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course1_id', models.IntegerField()),
                ('course2_id', models.IntegerField()),
                ('course1_classes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('course2_classes', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('result', models.BooleanField()),
            ],
            options={
                'indexes': [models.Index(fields=['course1_id', 'course2_id', 'course1_classes', 'course2_classes'], name='scheduler_c_course1_cef34f_idx')],
                'unique_together': {('course1_id', 'course2_id', 'course1_classes', 'course2_classes')},
            },
        ),
    ]
